---
- name: Ensure that the irssi package is installed (Darwin)
  tags: irssi
  homebrew:
    name: irssi
    state: present
  when: ansible_os_family == 'Darwin'

- name: Ensure that the irssi package is installed (Debian)
  tags: irssi
  become: true
  apt:
    name: irssi
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure that the irssi package is installed (RedHat)
  tags: irssi
  become: true
  yum:
    name: irssi
    state: present
  when: ansible_os_family == 'RedHat'

- name: Attempting to overlay irssi initial configuration directory
  tags: irssi
  file:
    path: "{{ irssi_config_dir }}"
    owner: "{{ irssi_config_owner }}"
    group: "{{ irssi_config_group }}"
    state: directory
    mode: 0700

- name: Attempting to overlay irssi scripts and autorun directories, if applicable
  tags: irssi
  file:
    path: "{{ item }}"
    owner: "{{ irssi_config_owner }}"
    group: "{{ irssi_config_group }}"
    state: directory
    mode: 0700
  register: irssi_scripts_create
  loop:
    - "{{ irssi_config_dir }}/scripts"
    - "{{ irssi_config_dir }}/scripts/autorun"
  loop_control:
    label: "{{ item }}"
  when: irssi_scripts|length > 0

- name: Attempting to overlay irssi scripts into the autorun directory, if applicable
  tags: irssi
  template:
    src: scripts.j2
    dest: "{{ irssi_config_dir }}/scripts/autorun/{{ item.name }}"
    owner: "{{ irssi_config_owner }}"
    group: "{{ irssi_config_group }}"
    mode: "{{ irssi_config_mode|default(0600) }}"
  loop: "{{ irssi_scripts }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name is defined
    - item.base64 is defined
    - irssi_scripts|length > 0

- name: Attempting to fetch and overlay irssi theme, if applicable
  tags: irssi
  get_url:
    url: "{{ irssi_theme }}"
    dest: "{{ irssi_config_dir }}"
    owner: "{{ irssi_config_owner }}"
    group: "{{ irssi_config_group }}"
    mode: 0600
  when: irssi_theme|length > 0

- name: Attempting to overlay irssi configurations
  tags: irssi
  template:
    src: config.j2
    dest: "{{ irssi_config_file }}"
    owner: "{{ irssi_config_owner }}"
    group: "{{ irssi_config_group }}"
    mode: 0600
...
